#!/usr/bin/env python
import subprocess
import os, sys

if __name__ == "__main__":
    path = "/usr/local/share/trimage/trimage.py" #yeah so this isn't the nices tway...
    subprocess.call([sys.executable, path] + sys.argv[1:])
